'use strict';
(()=>{
const rootURL=new URL('.',document.currentScript.src),C=window.HOME_FURNITURE_CORE;
if(!C||!window.HOME_FURNITURE_DATA)return;
const storageKey='w-dream-home:furniture:v1',originalSeed=C.validate(window.HOME_FURNITURE_DATA);
let data=C.clone(originalSeed),baseRevision=data.revision,dirty=false,editBuffer=null,conflict=null,storageOK=true,directory=null,busy=false,ui=null,currentRoom='all',filter='active',query='',lastMessage='',lastError=false,lastKnownStorage=null,localEdits=false;
const money=v=>Math.round(v).toLocaleString('zh-TW'),range=b=>b.min===b.max?'NT$ '+money(b.min):'NT$ '+money(b.min)+' – '+money(b.max);
const version=()=>window.HOME_LAYOUT?.proposal||window.HOME_LAYOUT?.version||new URLSearchParams(location.search).get('version')||'v1';
function incomingConflict(saved){const incoming=C.validate(saved.data);conflict={kind:'tab',a:{...saved,data:incoming},b:{data:C.clone(data),baseRevision:saved.baseRevision,dirty:true,editBuffer:C.clone(editBuffer)},aLabel:'使用另一分頁的清單',bLabel:'保留目前草稿'};}
function persist(){try{const current=localStorage.getItem(storageKey);if(current!==lastKnownStorage&&current){const other=JSON.parse(current);incomingConflict(other);lastKnownStorage=current;}if(conflict){if(ui)renderMain();status('另一版清單已有新變更，目前草稿尚未覆寫它。請先核對版本。',true);return;}const raw=JSON.stringify({data,baseRevision,dirty,editBuffer});localStorage.setItem(storageKey,raw);lastKnownStorage=raw;storageOK=true;}catch(e){storageOK=false;}status();}
try{const raw=localStorage.getItem(storageKey);lastKnownStorage=raw;if(raw){const saved=JSON.parse(raw),valid=C.validate(saved.data);if(saved.baseRevision===originalSeed.revision||(!saved.dirty&&!saved.editBuffer&&Date.parse(valid.updatedAt)>Date.parse(originalSeed.updatedAt))){data=valid;baseRevision=saved.baseRevision;dirty=!!saved.dirty;editBuffer=saved.editBuffer||null;}else if(saved.dirty||saved.editBuffer){conflict={a:{data:C.clone(originalSeed),baseRevision:originalSeed.revision,dirty:false,editBuffer:null},b:{...saved,data:valid,baseRevision:originalSeed.revision,dirty:true},aLabel:'使用專案檔',bLabel:'接續瀏覽器草稿'};}}}catch(e){lastMessage='瀏覽器草稿無法讀取，目前使用專案檔；可從備份檔重新載入。';}

function node(tag,attrs={},...children){const n=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k.startsWith('on')&&typeof v==='function')n[k]=v;else if(k==='className')n.className=v;else if(k==='text')n.textContent=v;else if(k in n)n[k]=v;else n.setAttribute(k,v);}for(const c of children.flat())if(c!==null&&c!==undefined)n.append(typeof c==='string'?document.createTextNode(c):c);return n;}
const button=(label,fn,cls='')=>node('button',{type:'button',text:label,onclick:fn,className:cls});
function status(message,error=false){if(message!==undefined){lastMessage=message;lastError=error;}if(!ui)return;const state=dirty||editBuffer?'尚未寫回專案':'與專案檔一致';ui.status.textContent=lastMessage||`${state} · ${storageOK?'草稿自動暫存於本瀏覽器':'本瀏覽器無法暫存，關閉前請儲存或匯出'}${directory?' · 已連結 '+directory.name:''}`;ui.status.classList.toggle('fcError',lastError||!storageOK);ui.save.disabled=busy||!!conflict;}
function touch(){localEdits=true;dirty=true;data.updatedAt=new Date().toISOString();lastMessage='';persist();}
function restoreConflict(useDraft){if(!conflict)return;const chosen=useDraft?(conflict.kind==='tab'?{data:C.clone(data),baseRevision:conflict.a.baseRevision,dirty:true,editBuffer:C.clone(editBuffer)}:conflict.b):conflict.a,other=useDraft?conflict.a:conflict.b;try{localStorage.setItem(storageKey+':older-draft',JSON.stringify(other));}catch(_){}data=C.validate(chosen.data);baseRevision=chosen.baseRevision;dirty=!!chosen.dirty;editBuffer=chosen.editBuffer||null;localEdits=!!dirty;conflict=null;lastKnownStorage=localStorage.getItem(storageKey);lastMessage='';lastError=false;persist();render();}

function variantNote(item){if(version()!=='v3')return item.currentNote;const specific={foyer:'V3：110×55×H90矮櫃，侧接頂掛衣桿、3帽鉤、少量鞋、鑰匙盤與包包檯面。30×40南端封閉轉角，電箱維修門獨立。',cat:'V3：取消獨立收藏室，改165×40玻璃展示＋155×60深收納；封閉轉角不計容量。原四面頂天的敘述為其他版本／來源紀錄。',island:'V3：300×95×H95；酒櫃、掃地機、IH及飲水各自分艙，全部朝西／冰箱。南端完整木皮；東側留膝34×104。備餐單槽外框55×45、內槽50×40、深20cm，產品型號待選；CLAR飲水龍頭獨立。'};return specific[item.room]||(item.room==='living'?'V3：83吋旋轉TV對齊沙發主座；Q6入櫃，Q7中心距204，雙重低音移至窗側。產品規格與預算仍共用。':item.currentNote);}
function modelTargets(item){const V=window.HOME_VIEWER,E=window.HOME_EQUIPMENT,targets=[];if(!V||!E)return targets;for(const key of item.modelKeys)for(const g of E.items)if(g.userData.equipment.key===key)targets.push(g);for(const originalName of item.modelSearch){const aliases={'玄關日常收納':'V3 玄關日常收納','收藏室行李箱門':'V3 深收納櫃・155×60','收藏室連續展示面':'V3 收藏玻璃展示櫃','玄關延伸玻璃展示櫃':'V3 收藏玻璃展示櫃'};const name=version()==='v3'?(aliases[originalName]||originalName):originalName;let found=null;V.scene.traverse(o=>{if(!found&&(o.name===name||o.userData.name===name))found=o;});if(found)targets.push(found);}return [...new Set(targets)];}
function close(){if(ui?.dialog)ui.dialog.close();else location.href=new URL(modelPath(version()),rootURL).href;}
function modelPath(v){return (v==='v3'?'提案/開放大中島/':v==='v2'?'提案/旋轉電視與直線中島/':'')+'index.html?layout='+(['v1','v2','v3'].includes(v)?v:'v1');}
function jump(item,target){const V=window.HOME_VIEWER,r=data.rooms.find(r=>r.id===item.room);if(V){if(ui?.dialog)ui.dialog.close();window.HOME_TOUR?.setMode('model');V.selectRoom(r?.modelRoom||'all');const g=target||modelTargets(item)[0];if(g)V.focusObject(g);}else{const url=new URL(modelPath(version()),rootURL);url.searchParams.set('catalogItem',item.id);location.href=url.href;}}
function jumpRoom(r){if(window.HOME_VIEWER){ui.dialog?.close();window.HOME_TOUR?.setMode('model');HOME_VIEWER.selectRoom(r.modelRoom);}else{const url=new URL(modelPath(version()),rootURL);url.searchParams.set('catalogRoom',r.modelRoom);location.href=url.href;}}
function exportFile(name,body,type){const u=URL.createObjectURL(new Blob([body],{type})),a=node('a',{href:u,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000);}
function exportBackup(){if(!applyEditor())return;exportFile('家具清單_備份.json',JSON.stringify(data,null,2),'application/json');status('已匯出備份。帶到另一台電腦後，可用「載入清單」接續編輯。');}
function applyEditor(){if(!editBuffer)return true;try{
 const {kind,id,fields}=editBuffer;
 if(kind==='item'){if(data.items.some(i=>i.id===id))data=C.updateItem(data,id,fields);else{const d=C.clone(data);d.items.push({id,room:fields.room,name:fields.name,brand:fields.brand,specs:fields.specs,priceText:fields.priceText,notes:fields.notes,status:fields.status,includeInBudget:fields.includeInBudget,archived:false,modelDirty:false,modelKeys:[],modelSearch:[],currentNote:'新建清單品項，尚未建立對應設備模型。',original:null,sourceAxId:null});data=C.validate(d);}}
 else if(kind==='room'){const d=C.clone(data);d.rooms.find(r=>r.id===id).notes=fields.notes;data=C.validate(d);}
 else{const d=C.clone(data);Object.assign(d.pending.find(p=>p.id===id),{name:fields.name,text:fields.text});data=C.validate(d);}
 editBuffer=null;touch();render();return true;
 }catch(e){status(e.message,true);return false;}}
function startEdit(kind,id){if(busy)return;if(editBuffer&&!applyEditor())return;let fields;if(kind==='item'){const i=data.items.find(i=>i.id===id);fields=i?Object.fromEntries(['name','brand','specs','priceText','notes','status','room','includeInBudget'].map(k=>[k,i[k]])):{name:'新設備',brand:'',specs:'',priceText:'',notes:'',status:'待確認',room:data.rooms.some(r=>r.id===currentRoom)?currentRoom:'whole',includeInBudget:true};}else if(kind==='room')fields={notes:data.rooms.find(r=>r.id===id).notes};else{const p=data.pending.find(p=>p.id===id);fields={name:p.name,text:p.text};}editBuffer={kind,id,fields};localEdits=true;persist();renderEditor();}
async function saveProject(){if(conflict||!applyEditor()||busy)return;try{
 if(!window.showDirectoryPicker){exportBackup();status('此瀏覽器不支援直接寫回資料夾，已改用JSON備份；可在支援的瀏覽器按「儲存到專案」。');return;}
 if(!directory)directory=await window.showDirectoryPicker({id:'w-dream-home-project',mode:'readwrite',startIn:'desktop'});
 if(conflict)throw Error('另一分頁已有新修改，請先核對版本。');busy=true;status('正在寫回 '+directory.name+'…');
 const operation=()=>C.saveDirectory(directory,data,baseRevision);const saved=navigator.locks?.request?await navigator.locks.request('w-home-furniture-save',operation):await operation();
 data=saved;baseRevision=saved.revision;localEdits=false;dirty=false;editBuffer=null;persist();render();status('已寫回 '+directory.name+'：家具清單.json 與家具清單網頁資料；上次版本也已保留。');
 }catch(e){if(e.name!=='AbortError')status('尚未完成儲存：'+e.message+' 草稿仍保留。',true);else status('已取消選擇資料夾，草稿仍保留。');}finally{busy=false;status();}}
async function importText(raw,label){if(busy)return;try{if(raw.length>4e6)throw Error('清單檔案過大');const next=C.validate(JSON.parse(raw));if((dirty||editBuffer)&&!window.confirm('目前有尚未寫回的修改。載入此檔會取代目前清單；需要保留時請先匯出備份。確定載入？'))return;try{localStorage.setItem(storageKey+':before-import',JSON.stringify({data,baseRevision,dirty,editBuffer}));}catch(_){}data=next;baseRevision=next.revision;localEdits=false;dirty=false;editBuffer=null;conflict=null;persist();render();status('已載入 '+label+'。');}catch(e){status('載入失敗，原清單保持不變：'+e.message,true);}}
function importFile(){if(busy)return;const input=node('input',{type:'file',accept:'.json,application/json',onchange:async()=>{const f=input.files?.[0];if(f)await importText(await f.text(),f.name);}});input.click();}
async function loadProject(){if(busy)return;try{if(!directory){if(!window.showDirectoryPicker){importFile();return;}directory=await window.showDirectoryPicker({id:'w-dream-home-project',mode:'readwrite',startIn:'desktop'});}const text=await C.readFile(directory,'家具清單.json');if(text===null)throw Error('資料夾沒有家具清單.json');await importText(text,directory.name+'／家具清單.json');}catch(e){if(e.name!=='AbortError')status(e.message,true);}}
function priceLabel(i){return i.priceText.replace(/\r?\n/g,' ＋ ')||'待填金額';}
function render(){if(!ui)return;renderSidebar();renderMain();renderEditor();status();}
function roomLabel(r){return version()==='v3'&&r.modelRoom==='collection'?'展示與深收納（原收藏室）':r.name;}
function renderSidebar(){ui.sidebar.replaceChildren();const active=data.items.filter(i=>!i.archived);for(const r of [{id:'all',name:'全屋總覽'},...data.rooms,{id:'pending',name:'選購條件'}]){const n=r.id==='pending'?data.pending.length:r.id==='all'?active.length:active.filter(i=>i.room===r.id).length;const b=button('',()=>{if(!applyEditor())return;currentRoom=r.id;query='';render();});b.append(node('span',{text:roomLabel(r)}),node('small',{text:String(n)}));b.setAttribute('aria-pressed',String(currentRoom===r.id));ui.sidebar.append(b);}}
function metric(label,val){return node('div',{className:'fcMetric'},node('small',{text:label}),node('strong',{text:val}));}
function renderMain(){const m=ui.main;m.replaceChildren();if(version()==='v3')m.append(node('p',{className:'fcNotes',text:'V3 共用原品項規格與預算；中島、玄關、收藏收納和影音擺位已變更。各筆明細的「本版配置」顯示新布局，原文仍保留。'}));if(conflict){m.append(node('div',{className:'fcConflict'},node('p',{text:'專案檔和先前瀏覽器草稿有不同版本，請選擇這次接續哪一份。'}),button(conflict.aLabel,()=>restoreConflict(false)),button(conflict.bLabel,()=>restoreConflict(true))));}
 if(currentRoom==='pending'){m.append(node('h3',{text:'規格已定，型號待選'}),node('p',{className:'fcMuted',text:'原文件的11組選購條件已搬入本專案，可直接更新；舊規劃仍須與目前3D及各品項的現行調整對照。'}));for(const p of data.pending)m.append(node('article',{className:'fcSelectionCard'},node('h4',{text:p.name}),node('p',{text:p.text}),button('編輯條件',()=>startEdit('pending',p.id))));return;}
 const room=data.rooms.find(r=>r.id===currentRoom),items=data.items.filter(i=>!room||i.room===room.id),b=C.budget(items);
 m.append(node('h3',{text:room?roomLabel(room):'家具與設備總覽'}),node('p',{className:'fcMuted',text:'品牌、规格、金額與備註可直接編輯。金額以整列計算；含工程、不採用與資料參考不重複加總。'}),node('div',{className:'fcMetrics'},metric('已填預算範圍',range(b)),metric('待填／待報價',String(b.pending)),metric('金額待釐清',String(b.invalid))));
 if(room){m.append(node('div',{className:'fcNotes',text:room.notes}),node('div',{className:'fcRowActions'},button('查看此區3D',()=>jumpRoom(room)),button('編輯區域備註',()=>startEdit('room',room.id))));const details=node('details',{},node('summary',{text:'查看匯入時的區域說明'}),node('pre',{className:'fcSource',text:room.sourceOverview}));m.append(details);}
 else{const details=node('details',{},node('summary',{text:'各區已填金額分布'})),bars=node('div',{className:'fcBudgetList'});for(const r of data.rooms){const rb=C.budget(data.items.filter(i=>i.room===r.id));bars.append(node('div',{className:'fcBudgetLine'},node('span',{text:roomLabel(r)}),node('progress',{value:Math.max(0,rb.max),max:Math.max(1,b.max),'aria-label':r.name+'預算'}),node('span',{text:range(rb)})));}details.append(bars);m.append(details);}
 const search=node('input',{type:'search',placeholder:'搜尋品項、型號、規格或備註',value:query,'aria-label':'搜尋家具',oninput:()=>{query=search.value;renderRows();}}),sel=node('select',{'aria-label':'清單篩選',onchange:()=>{filter=sel.value;renderRows();}});for(const [value,label] of [['active','全部未封存'],['purchase','採購與設備'],['pending','待填價格'],['model','模型待同步'],['unused','不採用'],['archived','已封存']])sel.append(node('option',{value,text:label,selected:filter===value}));m.append(node('div',{className:'fcFilters'},search,sel,button('＋ 新增品項',()=>startEdit('item','item-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)))));
 ui.resultCount=node('p',{className:'fcMuted'});ui.tbody=node('tbody');m.append(ui.resultCount,node('div',{className:'fcTableWrap'},node('table',{className:'fcTable'},node('thead',{},node('tr',{},...['品項／品牌','狀態','整列金額','操作'].map(t=>node('th',{scope:'col',text:t})))),ui.tbody)));
 m.append(node('p',{className:'fcSmallNote',text:'匯入來源：2026/09/10 上午11:08本機備份。原文保存在各筆明細，後續設計另註。規格變更會標記模型待核對，修改價格與備註不會改動3D尺寸。'}));renderRows();}
function renderRows(){if(!ui.tbody||currentRoom==='pending')return;const term=query.trim().toLowerCase();const rows=data.items.filter(i=>(currentRoom==='all'||i.room===currentRoom)&&(filter==='archived'?i.archived:!i.archived)&&(filter!=='purchase'||!['不採用','資料參考'].includes(i.status))&&(filter!=='pending'||C.parsePrice(i.priceText).kind==='pending')&&(filter!=='model'||i.modelDirty)&&(filter!=='unused'||i.status==='不採用')&&(!term||[i.name,i.brand,i.specs,i.notes,i.currentNote].join('\n').toLowerCase().includes(term)));ui.resultCount.textContent=`顯示 ${rows.length} 筆`;ui.tbody.replaceChildren();
 for(const i of rows){const p=C.parsePrice(i.priceText),state=node('td',{},node('span',{className:'fcTag',text:i.status}));if(i.modelDirty)state.append(node('span',{className:'fcTag fcPending',text:'模型待同步'}));if(!i.includeInBudget)state.append(node('small',{text:'不列入預算'}));const actions=node('div',{className:'fcRowActions'},button('查看／編輯',()=>startEdit('item',i.id)),button(i.modelKeys.length||i.modelSearch.length?'3D定位':'查看區域',()=>jump(i)));ui.tbody.append(node('tr',{className:['不採用','資料參考'].includes(i.status)?'fcInactive':''},node('td',{},node('span',{className:'fcName',text:i.name}),node('small',{text:i.brand}),currentRoom==='all'?node('span',{className:'fcTag',text:data.rooms.find(r=>r.id===i.room)?.name}):null),state,node('td',{className:'fcMoney',text:priceLabel(i)},p.kind==='invalid'?node('small',{text:'格式待釐清，未計入總額'}):null),node('td',{},actions)));}
 if(!rows.length)ui.tbody.append(node('tr',{},node('td',{colSpan:4,className:'fcEmpty',text:'沒有符合條件的品項。可切換區域、篩選或新增。'})));}
function renderEditor(){if(!ui)return;const e=ui.editor;e.replaceChildren();e.hidden=!editBuffer;ui.layout.classList.toggle('fcHasEditor',!!editBuffer);if(!editBuffer)return;const {kind,id,fields}=editBuffer,existing=data.items.find(i=>i.id===id);e.append(node('h3',{text:kind==='item'?'品項明細':kind==='room'?'區域備註':'選購條件'}));
 function field(key,label,type='text'){let input;if(type==='room'||type==='status'){input=node('select');for(const o of (type==='room'?data.rooms.map(r=>({value:r.id,text:r.name})):C.statuses.map(s=>({value:s,text:s}))))input.append(node('option',{...o,selected:fields[key]===o.value}));}else if(type==='textarea')input=node('textarea',{value:fields[key],className:key==='specs'?'fcSpecs':''});else input=node('input',{type,value:fields[key]??'',checked:type==='checkbox'?!!fields[key]:undefined});input.oninput=()=>{fields[key]=type==='checkbox'?input.checked:input.value;lastMessage='';persist();};input.onchange=input.oninput;e.append(node('label',{className:type==='checkbox'?'fcCheck':''},type==='checkbox'?input:label,type==='checkbox'?label:input));}
 if(kind==='item'){field('name','品項名稱');field('room','區域','room');field('brand','品牌與型號','textarea');field('status','目前狀態','status');field('priceText','整列金額（如170000、15000–30000；不乘數量）');field('includeInBudget','納入預算總計','checkbox');field('specs','規格與安裝條件','textarea');field('notes','我的備註／採購進度','textarea');if(existing?.currentNote)e.append(node('div',{className:'fcNotes',text:'本版配置（共用規格另列）\n'+variantNote(existing)}));const targets=existing?modelTargets(existing):[];if(targets.length){e.append(node('h4',{text:'對應3D設備'}));for(const [n,g] of targets.entries()){const eq=g.userData.equipment;e.append(button('定位 '+(n+1)+' · '+g.name,()=>{if(applyEditor())jump(data.items.find(i=>i.id===id),g);}));if(eq)e.append(node('div',{className:'fcModelSpecs',text:`目前模型：${eq.w} 寬 × ${eq.d} 深 × ${eq.h} 高 cm\n${eq.name}`}));}}
 if(existing?.original)e.append(node('details',{},node('summary',{text:'查看Claude匯入原文'}),node('pre',{className:'fcSource',text:[existing.original.name,existing.original.brand,existing.original.specs,'原金額：'+existing.original.priceText].join('\n\n')})));
 if(existing)e.append(button(existing.archived?'恢復此品項':'封存此品項',()=>{if(!applyEditor())return;data=C.updateItem(data,id,{archived:!data.items.find(i=>i.id===id).archived});touch();render();}));
 }else if(kind==='room')field('notes','目前區域設計與備註','textarea');else{field('name','條件名稱');field('text','內容','textarea');}
 e.append(node('div',{className:'fcEditorActions'},button('套用修改',()=>applyEditor(),'fcPrimary'),button('取消這次編輯',()=>{editBuffer=null;lastMessage='';persist();renderEditor();})));}
function build(){if(ui)return;const standalone=document.getElementById('catalogStandalone'),dialog=standalone?null:node('dialog',{className:'fcDialog fcApp','aria-label':'家具與設備清單'}),app=standalone||dialog;app.classList.add('fcApp');if(dialog)document.body.append(dialog);const style=node('link',{rel:'stylesheet',href:new URL('furniture.css?v=20260910-ui',rootURL).href});document.head.append(style);
 const save=button('儲存到專案',saveProject,'fcPrimary'),statusNode=node('p',{className:'fcStatus',role:'status','aria-live':'polite'});
 const files=node('details',{className:'fcFileMenu'},node('summary',{text:'匯入／匯出'}),node('div',{className:'fcFileOptions'},button('載入專案檔',loadProject),button('載入清單',importFile),button('匯出備份',exportBackup),button('匯出文字',()=>{if(applyEditor())exportFile('家具清單.md',C.markdown(data),'text/markdown;charset=utf-8');})));
 const header=node('div',{className:'fcHeader'},node('div',{className:'fcTitleRow'},button('← 空間設計',()=>{if(applyEditor())close();},'fcBack'),node('div',{},node('h2',{text:'家具與設備清單'}),node('p',{className:'fcSubtitle',text:'V1、V2 共用 · 規格、採購與預算'}))),node('div',{className:'fcActions'},files,save),statusNode),sidebar=node('nav',{className:'fcSidebar','aria-label':'家具區域'}),main=node('section',{className:'fcMain'}),editor=node('aside',{className:'fcEditor',hidden:true,'aria-label':'編輯家具'}),layout=node('div',{className:'fcLayout'},sidebar,main,editor);app.append(header,layout);ui={app,dialog,save,status:statusNode,sidebar,main,editor,layout};dialog?.addEventListener('cancel',()=>persist());render();}
function open(options){window.HOME_TOUR?.setMode('model');if(options?.room&&applyEditor()){currentRoom=options.room==='all'?'all':data.rooms.find(r=>r.modelRoom===options.room)?.id||'all';query='';}build();render();if(ui.dialog&&!ui.dialog.open)ui.dialog.showModal();status();}
function init(){const host=document.getElementById('catalogStandalone');if(host){build();return;}const bar=document.getElementById('layoutSwitch');if(bar){const b=button('家具與設備清單',open,'equipmentAction');b.id='homeFurnitureCatalog';bar.append(b);}const params=new URLSearchParams(location.search),id=params.get('catalogItem'),room=params.get('catalogRoom');if(id){const i=data.items.find(i=>i.id===id);if(i)jump(i);}else if(room&&HOME_VIEWER.rooms.some(r=>r.id===room)){HOME_TOUR.setMode('model');HOME_VIEWER.selectRoom(room);}}
window.addEventListener('storage',e=>{if(e.key!==storageKey||!e.newValue)return;try{const next=JSON.parse(e.newValue);lastKnownStorage=e.newValue;if(localEdits||editBuffer){incomingConflict(next);render();status('另一分頁有新修改，請選擇要接續的版本。',true);}else{data=C.validate(next.data);baseRevision=next.baseRevision;dirty=!!next.dirty;editBuffer=next.editBuffer||null;render();status('已接收另一個分頁的清單更新。');}}catch(_){}});

window.addEventListener('beforeunload',e=>{persist();if(dirty||editBuffer){e.preventDefault();e.returnValue='';}});
window.HOME_CATALOG={open,modelTargets,jumpToModel:jump,getState:()=>({data:C.clone(data),baseRevision,dirty,editBuffer:C.clone(editBuffer),storageOK}),saveProject,importText};
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();
