'use strict';
(()=>{const T=THREE,V=HOME_VIEWER,$=id=>document.getElementById(id);const host=document.createElement('div');host.id='panoramaHost';host.innerHTML='<canvas id="panoCanvas" tabindex="0" aria-label="360度全景，拖曳或方向鍵環視"></canvas><div id="panoStatus" role="status"></div><div id="panoTop"><span>360° · 固定視點環視</span><button data-pano-time="day">日間</button><button data-pano-time="night">夜間</button><button id="panoQuality" aria-label="切換全景解析度">高清 · 7K</button><button id="panoFull">放大觀看</button></div><div id="panoBottom"><button data-pano="left" aria-label="向左看">←</button><button data-pano="right" aria-label="向右看">→</button><button data-pano="in" aria-label="放大">＋</button><button data-pano="out" aria-label="縮小">−</button><button data-pano="home">回正</button><button id="panoReference">對照格局底圖</button></div><div id="panoNote">拖曳轉頭 · 滾輪縮放 · 連續行走請選「真人步行」</div>';$('scenePanel').querySelector('main').appendChild(host);
const style=document.createElement('style');style.textContent='.viewTabs{flex-wrap:wrap}.sceneToolbar{gap:8px}#scenePanel main{position:relative}#panoramaHost{display:none;position:absolute;inset:0;background:#171d20;z-index:5;overflow:hidden}#scenePanel[data-mode=panorama] #panoramaHost{display:block}#scenePanel[data-mode=panorama] #cameraControls,#scenePanel[data-mode=panorama] #photoControls,#scenePanel[data-mode=panorama] #caption,#scenePanel[data-mode=panorama] #photoBadge{display:none!important}#panoCanvas{width:100%;height:100%;touch-action:none;cursor:grab;display:block}#panoTop,#panoBottom{position:absolute;display:flex;gap:6px;align-items:center;background:#172026d9;border-radius:8px;padding:6px;color:#eee}#panoTop{top:14px;left:14px;right:14px;flex-wrap:wrap}#panoTop span{margin-right:auto;font-size:12px}#panoBottom{bottom:38px;left:50%;transform:translateX(-50%);max-width:96%;flex-wrap:wrap;justify-content:center;width:max-content}#panoramaHost button{border:1px solid #687278;border-radius:5px;padding:8px 11px;background:#28343a;color:white;cursor:pointer}#panoramaHost button.active{background:#d3e2de;color:#142022}#panoStatus{position:absolute;top:75px;left:16px;color:white;background:#263137df;padding:8px;border-radius:6px;font-size:12px}#panoStatus:empty{display:none}#panoNote{position:absolute;bottom:9px;left:12px;font-size:11px;color:white;background:#172026b8;padding:4px}#panoramaHost:fullscreen{width:100vw;height:100vh}';document.head.appendChild(style);
const toggle=document.createElement('button');toggle.dataset.viewmode='panorama';toggle.textContent='360°照片環視';document.querySelector('[data-viewmode="photo"]').parentElement.appendChild(toggle);toggle.onclick=()=>{if(V.getCurrent()==='all')V.selectRoom('living');HOME_TOUR.setMode('panorama');};
const renderer=new T.WebGLRenderer({canvas:$('panoCanvas'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));const scene=new T.Scene(),camera=new T.OrthographicCamera(-1,1,1,-1,0,1);
const uniforms={tex:{value:null},yaw:{value:0},pitch:{value:0},fov:{value:55*Math.PI/180},aspect:{value:1}};
const material=new T.ShaderMaterial({uniforms,vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=vec4(position,1.);}',fragmentShader:'uniform sampler2D tex;uniform float yaw,pitch,fov,aspect;varying vec2 v;void main(){vec2 xy=(v-.5)*2.;vec3 d=normalize(vec3(xy.x*aspect*tan(fov*.5),xy.y*tan(fov*.5),-1.));float c=cos(pitch),s=sin(pitch);d=vec3(d.x,d.y*c-d.z*s,d.y*s+d.z*c);c=cos(yaw);s=sin(yaw);d=vec3(d.x*c-d.z*s,d.y,d.x*s+d.z*c);vec2 uv=vec2(fract(atan(d.x,-d.z)/6.2831853+.5),asin(clamp(d.y,-1.,1.))/3.14159265+.5);gl_FragColor=texture2D(tex,uv);}'});scene.add(new T.Mesh(new T.PlaneGeometry(2,2),material));
let quality=renderer.capabilities.maxTextureSize>=7096?'hd':'standard',textureSize=null;let active=false,time='day',reference=false,request=0,loaded=false,currentRoom='',drag=null;const cache=new Map();function draw(){if(active&&loaded)renderer.render(scene,camera);}function resize(){const r=host.getBoundingClientRect();if(r.width&&r.height){renderer.setSize(r.width,r.height,false);uniforms.aspect.value=r.width/r.height;draw();}}new ResizeObserver(resize).observe(host);
function reset(){const d=new T.Vector3();V.camera.getWorldDirection(d);uniforms.yaw.value=Math.atan2(d.x,-d.z);uniforms.pitch.value=0;uniforms.fov.value=55*Math.PI/180;draw();}
function load(){const id=V.getCurrent();if(id==='all')return;const ticket=++request;currentRoom=id;loaded=false;canvas.style.opacity='.35';$('panoStatus').textContent='載入全景…';renderer.clear();const url=reference?'全景底圖/'+id+'.png':quality==='hd'?'360全景高清/'+id+'-'+time+'.jpg':'360全景/'+id+'-'+time+'.png';$('panoQuality').textContent=quality==='hd'?'高清 · 7K':'標準';$('panoQuality').disabled=reference||renderer.capabilities.maxTextureSize<7096;$('panoQuality').classList.toggle('active',quality==='hd'&&!reference);document.querySelectorAll('[data-pano-time]').forEach(b=>b.classList.toggle('active',b.dataset.panoTime===time));$('panoReference').textContent=reference?'返回寫實全景':'對照格局底圖';
function ready(tex){if(ticket!==request)return;uniforms.tex.value=tex;textureSize=[tex.image.width,tex.image.height];loaded=true;$('panoStatus').textContent='';canvas.style.opacity='1';resize();}if(cache.has(url)){ready(cache.get(url));return;}sourceURL(url).then(data=>new T.TextureLoader().load(data,tex=>{if(ticket!==request){tex.dispose();return;}tex.minFilter=T.LinearFilter;tex.magFilter=T.LinearFilter;tex.generateMipmaps=false;cache.set(url,tex);while(cache.size>2){const key=cache.keys().next().value;if(key===url)break;cache.get(key).dispose();cache.delete(key);}ready(tex);},undefined,()=>{if(ticket===request){if(quality==='hd'&&!reference){quality='standard';load();}else $('panoStatus').textContent='此全景無法載入，請確認全景資料夾與網頁放在一起。';}})).catch(()=>{if(ticket===request){if(quality==='hd'&&!reference){quality='standard';load();}else $('panoStatus').textContent='全景檔案讀取失敗，請保留360全景與全景底圖資料夾。';}});}
window.PANO_ASSETS={};const sourceRequests=new Map();function sourceURL(url){if(location.protocol!=="file:")return Promise.resolve(url);if(sourceRequests.has(url))return sourceRequests.get(url);const promise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=url.replace(/\.(png|jpg)$/,'.js');script.onload=()=>{const data=window.PANO_ASSETS[url];delete window.PANO_ASSETS[url];script.remove();sourceRequests.delete(url);if(data)resolve(data);else reject(new Error('Missing panorama'));};script.onerror=()=>{script.remove();sourceRequests.delete(url);reject(new Error('Asset missing'));};document.head.appendChild(script);});sourceRequests.set(url,promise);return promise;}
function enter(){if(active)return;active=true;reset();load();}function exit(){active=false;drag=null;}window.addEventListener('roomchange',()=>{if(active){if(V.getCurrent()==='all'){HOME_TOUR.setMode('model');return;}reset();load();}});
$('panoQuality').onclick=()=>{quality=quality==='hd'?'standard':'hd';load();};document.querySelectorAll('[data-pano-time]').forEach(b=>b.onclick=()=>{time=b.dataset.panoTime;reference=false;load();});$('panoReference').onclick=()=>{reference=!reference;load();};$('panoFull').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else host.requestFullscreen().catch(()=>{document.querySelector('.workspace').classList.add('planhidden');resize();});};
function move(a){if(a==='home')reset();else if(a==='left'||a==='right')uniforms.yaw.value+=a==='left'?-.18:.18;else uniforms.fov.value=Math.max(.5,Math.min(1.45,uniforms.fov.value+(a==='in'?-.08:.08)));draw();}document.querySelectorAll('[data-pano]').forEach(b=>b.onclick=()=>move(b.dataset.pano));
const canvas=$('panoCanvas');canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.focus();};canvas.onpointermove=e=>{if(!drag)return;uniforms.yaw.value-=(e.clientX-drag.x)*.004;uniforms.pitch.value=Math.max(-1.48,Math.min(1.48,uniforms.pitch.value+(e.clientY-drag.y)*.004));drag={x:e.clientX,y:e.clientY};draw();};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();move(e.deltaY<0?'in':'out');},{passive:false});canvas.onkeydown=e=>{const a={ArrowLeft:'left',ArrowRight:'right','+':'in','-':'out',Home:'home'}[e.key];if(a){e.preventDefault();move(a);}};
window.HOME_PANORAMA={enter,exit,capture:()=>renderer.domElement.toDataURL('image/png'),getState:()=>({active,time,reference,loaded,quality,textureSize,maxTextureSize:renderer.capabilities.maxTextureSize,room:currentRoom,yaw:uniforms.yaw.value,pitch:uniforms.pitch.value,fov:uniforms.fov.value}),move};
})();

