'use strict';
(()=>{
const V=window.HOME_VIEWER,T=window.THREE,$=id=>document.getElementById(id);if(!V)return;
const rooms=V.rooms, ns='http://www.w3.org/2000/svg';
const areas={bed:[[-75,0],[405,0],[405,282],[-75,282]],closet:[[415,0],[745,0],[745,260],[580,260],[580,207],[415,207]],study:[[755,0],[1085,0],[1085,365],[755,365]],bath1:[[-75,293],[305,293],[305,483],[-75,483]],bath2:[[415,217],[570,217],[570,365],[415,365]],storage:[[580,270],[745,270],[745,365],[580,365]],kitchen:[[0,493],[215,493],[215,955],[0,955]],back:[[-210,498],[-8,498],[-8,899],[-210,899]],collection:[[215,753],[450,753],[450,880],[435,880],[435,955],[215,955]],entry:[[450,805],[715,805],[715,955],[545,955],[545,880],[450,880]],living:[[315,375],[1085,375],[1085,955],[715,955],[715,753],[315,753]]};
{areas.collection=[[215,753],[450,753],[450,803],[545.2,803],[545.2,875],[435,875],[435,955],[215,955]];areas.entry=[[555.2,803],[715,803],[715,955],[545.2,955],[545.2,885],[555.2,885]];}
areas.island=[[400,452],[670,452],[670,502],[400,502]];
const centers={island:[535,472],bed:[150,160],closet:[635,135],study:[930,185],bath1:[60,365],bath2:[490,300],storage:[665,320],kitchen:[105,720],back:[-108,610],collection:[346,842],entry:[610,876],living:[860,720]};
const svg=document.createElementNS(ns,'svg');svg.id='floorplan';svg.setAttribute('viewBox','-250 -70 1480 1090');svg.setAttribute('aria-label','裝潢平面圖，點選房間進入3D');
svg.innerHTML='<image id="planTexture" x="-250" y="-70" width="1480" height="1090"/><g id="hotspots"></g><g id="cameraPin" pointer-events="none"><path d="M0 0 L-20 -48 Q0 -64 20 -48 Z" fill="#b5daca55" stroke="#b5daca"/><circle r="8" fill="#d2f7e7" stroke="#142c27" stroke-width="3"/></g><text x="610" y="1010" fill="#c9d2d5" text-anchor="middle" font-size="22">↑ 入戶 · A1-14F</text>';
$('planstage').appendChild(svg);
const sourceImg=document.createElementNS(ns,'image');sourceImg.id='sourceImage';sourceImg.style.display='none';svg.insertBefore(sourceImg,svg.querySelector('#hotspots'));
const compare=document.createElement('div');compare.className='sourceCompare';compare.innerHTML='<button data-source="model" class="active">裝潢平面</button><button data-source="walls">客變隔間原圖</button><button data-source="furniture">客變配置原圖</button>';$('planstage').before(compare);
let planSource='model';function showSource(kind){planSource=kind;if($('planDoors'))$('planDoors').style.display=kind==='model'?'':'none';const original=kind!=='model';$('planTexture').style.display=original?'none':'';sourceImg.style.display=original?'':'none';if(original){const a=window.SOURCE_PLAN[kind];for(const k of ['x','y','width','height'])sourceImg.setAttribute(k,a[{width:'w',height:'h'}[k]||k]);sourceImg.setAttribute('href',a.url);}document.querySelectorAll('[data-source]').forEach(b=>b.classList.toggle('active',b.dataset.source===kind));document.querySelector('.planIntro').textContent=original?'原 PDF 對位顯示；家具以後續確認變更為準。':'100 cm 水平剖切；原牆、柱與門窗可切換原圖核對。';}compare.querySelectorAll('button').forEach(b=>b.onclick=()=>showSource(b.dataset.source));

function el(tag,attrs){const e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e;}
Object.entries(areas).forEach(([id,pts])=>{const r=rooms.find(r=>r.id===id),g=el('g',{class:'planroom',role:'button',tabindex:'0','aria-label':'進入'+r.n,'data-room':id});g.appendChild(el('polygon',{points:pts.map(p=>p.join(',')).join(' ')}));const [x,y]=centers[id],label=el('g',{class:'planlabel'});label.appendChild(el('rect',{x:x-80,y:y-25,width:160,height:50,rx:10}));const text=el('text',{x,y:y+10,'text-anchor':'middle'});text.textContent=r.id==='island'?'雙面玻璃櫃':r.n.replace('・中島','');label.appendChild(text);g.appendChild(label);const choose=()=>{V.selectRoom(id);setMode(mode==='walk'?'walk':'model');if(innerWidth<760)$('scenePanel').scrollIntoView({behavior:'smooth',block:'start'});};g.onclick=choose;g.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();choose();}};$('hotspots').appendChild(g);});
// Render top-down material plan from the very same geometry, without AI changing room footprints.
function planImage(){const url=V.capturePlan();$('planTexture').setAttribute('href',url);return url;}
const doorOverlay=document.createElementNS(ns,'g');doorOverlay.id='planDoors';doorOverlay.setAttribute('pointer-events','none');svg.insertBefore(doorOverlay,svg.querySelector('#hotspots'));V.doorPlan().forEach(d=>{const poly=document.createElementNS(ns,'polygon');poly.setAttribute('points',d.points.map(p=>p.join(',')).join(' '));poly.setAttribute('fill','#273239');poly.setAttribute('stroke','#101a20');poly.setAttribute('stroke-width','1.5');doorOverlay.appendChild(poly);});
let planURL=planImage(),mode='model',photoZoom=1,photoX=0,photoY=0;
const links={all:['living','bed','kitchen','study'],island:['living','kitchen','bed'],living:['island','study','kitchen','entry','bed'],entry:['living','collection'],bed:['bath1','closet','living'],closet:['bed','bath2'],bath1:['bed'],bath2:['living','closet'],study:['living'],kitchen:['living','back'],back:['kitchen'],collection:['entry'],storage:['living']};
let referenceShown=false;function resetPhoto(){if(mode==='photo')$('photo').src=currentURL();referenceShown=false;if($('photoReference'))$('photoReference').textContent='反向180°';photoZoom=1;photoX=photoY=0;photoTransform();}
const referenceButton=document.createElement('button');referenceButton.id='photoReference';referenceButton.hidden=true;referenceButton.textContent='反向180°';$('photoControls').appendChild(referenceButton);referenceButton.onclick=()=>{referenceShown=!referenceShown;$('photo').src=currentURL(V.getCurrent(),referenceShown);$('photoDownload').href=currentURL(V.getCurrent(),referenceShown);referenceButton.textContent=referenceShown?'返回正向':'反向180°';};
function photoTransform(){$('photo').style.transform=`translate(${photoX}px,${photoY}px) scale(${photoZoom})`;}
function currentURL(id=V.getCurrent(),reverse=false){return id==='all'?planURL:(window.HOME_AI_PHOTOS?.[HOME_LAYOUT.version]?.find(p=>p.room===id)?.src||planURL);}
function setMode(m){if(!['model','photo','walk'].includes(m))m='model';mode=m;$('scenePanel').dataset.mode=m;document.querySelectorAll('[data-viewmode]').forEach(b=>{const active=b.dataset.viewmode===m;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});$('photoBadge').hidden=m!=='photo';$('cameraControls').hidden=m==='photo';$('photoControls').hidden=m!=='photo';$('detail').style.display='none';if(m==='photo'){$('photo').src=currentURL();resetPhoto();}}
const exportModel=$('export').onclick;$('export').onclick=()=>{if(mode==='photo')$('photoDownload').click();else exportModel();};
document.querySelectorAll('[data-viewmode]').forEach(b=>b.onclick=()=>setMode(b.dataset.viewmode));
function roomChanged(id){document.querySelectorAll('.planroom').forEach(g=>{g.classList.toggle('selected',g.dataset.room===id);g.setAttribute('aria-pressed',g.dataset.room===id);});$('activeRoom').textContent=rooms.find(r=>r.id===id).n;$('roomCounter').textContent=String(rooms.findIndex(r=>r.id===id)+1).padStart(2,'0')+' / '+rooms.length;$('nearby').replaceChildren();(links[id]||[]).forEach(to=>{const b=document.createElement('button');b.textContent='↗ '+rooms.find(r=>r.id===to).n;b.onclick=()=>V.selectRoom(to);$('nearby').appendChild(b);});if(mode==='photo'){$('photo').src=currentURL();resetPhoto();}document.querySelectorAll('.galleryItem').forEach(b=>b.classList.toggle('active',b.dataset.room===id));$('photoDownload').href=currentURL();$('photoDownload').download='W夢想之家_'+id+'_最新視角.jpg';}
window.addEventListener('roomchange',e=>roomChanged(e.detail));
$('photo').onload=()=>{$('photoError').hidden=true;};$('photo').onerror=()=>{$('photoError').hidden=false;};
$('planToggle').onclick=()=>{document.querySelector('.workspace').classList.toggle('planhidden');$('planToggle').textContent=document.querySelector('.workspace').classList.contains('planhidden')?'顯示平面圖':'收起平面圖';};
$('planHome').onclick=()=>{V.selectRoom('all');setMode('model');};
$('planExport').onclick=()=>{const a=document.createElement('a');a.download='A1-14F_'+(window.HOME_LAYOUT?.version||'v1')+'_裝潢平面圖.svg';const clone=svg.cloneNode(true);clone.querySelector('#cameraPin').remove();clone.querySelectorAll('.planroom > polygon').forEach(e=>{e.setAttribute('fill','transparent');e.setAttribute('stroke','none');});clone.querySelectorAll('.planlabel rect').forEach(e=>e.setAttribute('fill','#151b20d9'));clone.querySelectorAll('.planlabel text').forEach(e=>{e.setAttribute('fill','#edf4f4');e.setAttribute('font-size','30');});const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));a.href=url;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);};
function move(action){V.nudge(action);}
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>move(b.dataset.camera));
document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{if(b.dataset.photo==='reset')resetPhoto();else{photoZoom=Math.max(1,Math.min(3,photoZoom+(b.dataset.photo==='in'?.2:-.2)));photoTransform();}});
let drag=null;$('photoStage').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};$('photoStage').setPointerCapture(e.pointerId);};$('photoStage').onpointermove=e=>{if(!drag||photoZoom===1)return;photoX=Math.max(-500,Math.min(500,photoX+e.clientX-drag.x));photoY=Math.max(-300,Math.min(300,photoY+e.clientY-drag.y));drag={x:e.clientX,y:e.clientY};photoTransform();};$('photoStage').onpointerup=()=>drag=null;$('photoStage').onpointercancel=()=>drag=null;
rooms.forEach(r=>{const b=document.createElement('button');b.className='galleryItem';b.dataset.room=r.id;b.innerHTML=`<img loading="lazy" src="${currentURL(r.id)}" alt="${r.n}裝潢效果"><span>${r.n}</span>`;b.onclick=()=>{V.selectRoom(r.id);setMode('photo');};$('filmstrip').appendChild(b);});
let pinAt=-Infinity,pinKey='';const pinDirection=new T.Vector3();function pin(now=performance.now()){
 requestAnimationFrame(pin);if(document.hidden||now-pinAt<100||$('planPanel').hidden)return;pinAt=now;
 const p=V.camera.position;V.camera.getWorldDirection(pinDirection);const x=p.x+482.5,y=p.z+480;
 const key=`${x.toFixed(2)},${y.toFixed(2)},${Math.atan2(pinDirection.x,-pinDirection.z).toFixed(5)},${V.getCurrent()}`;
 if(key===pinKey)return;pinKey=key;$('cameraPin').setAttribute('transform',`translate(${x},${y}) rotate(${Math.atan2(pinDirection.x,-pinDirection.z)*180/Math.PI})`);$('cameraPin').style.display=V.getCurrent()==='all'?'none':'';
}pin();
roomChanged('all');setMode('model');window.HOME_TOUR={showSource,getSource:()=>planSource,setMode,planImage:()=>planURL,areas,getMode:()=>mode};
// Refresh after the shared material modules finish; initial plan predates flooring.js.
window.addEventListener('load',async()=>{await window.HOME_FLOORING?.ready;planURL=planImage();if(mode==='photo'&&V.getCurrent()==='all')$('photo').src=planURL;const thumb=document.querySelector('.galleryItem[data-room="all"] img');if(thumb)thumb.src=planURL;});
})();

