"""Validate and assemble the explicit GitHub Pages file set. Standard library only."""
from pathlib import Path, PurePosixPath
from html.parser import HTMLParser
from urllib.parse import urljoin, urlsplit, unquote
import argparse, json, re, shutil

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / '.github/publish-files.json'

class Links(HTMLParser):
    def __init__(self):
        super().__init__(); self.base = ''; self.links = []
    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == 'base': self.base = attrs.get('href', '')
        elif tag in {'a','script','img','link','iframe','source'}:
            self.links += [attrs[k] for k in ('href','src') if attrs.get(k)]

def local_links(name):
    parser = Links(); parser.feed((ROOT / name).read_text(encoding='utf-8-sig'))
    base = urljoin('https://site.invalid/' + name, parser.base)
    for link in parser.links:
        url = urlsplit(urljoin(base, link))
        if url.hostname == 'site.invalid':
            target = unquote(url.path).lstrip('/')
            if target and not target.endswith('/'): yield target

def entries():
    data = json.loads(MANIFEST.read_text(encoding='utf-8'))
    site = set(data['site']); repo = site | set(data['repositoryOnly'])
    assert len(site) == len(data['site']), 'Duplicate site entries'
    for name in repo:
        p = PurePosixPath(name)
        if p.is_absolute() or '..' in p.parts or '\\' in name:
            raise ValueError('Unsafe path in manifest: ' + name)
        source = ROOT / name
        if not source.is_file() or source.is_symlink(): raise ValueError('Missing or linked file: ' + name)
        if any(x in {'.git','node_modules','__pycache__','.codex','.agents'} for x in p.parts): raise ValueError('Local-only file: ' + name)
        if source.suffix.lower() in {'.pdf','.zip','.log','.tmp','.pyc'} or p.name.startswith('.env'): raise ValueError('Excluded source or temporary file: ' + name)
        if source.stat().st_size >= 95 * 1024 * 1024: raise ValueError('Oversized file: ' + name)
    return data, site, repo

def verify(site):
    count = 0
    for name in sorted(site):
        if name.endswith('.html'):
            for target in local_links(name):
                if target not in site: raise ValueError(f'Missing site dependency: {name} -> {target}')
                count += 1
    for v in ('v1','v2'):
        for room in ('living','island','entry','kitchen','bed','closet','study','collection','bath1','bath2','storage','back'):
            for direction in ('A','B'):
                if f'最新版導覽/{v}/{room}-{direction}.jpg' not in site: raise ValueError('Missing historical room reference')
    for required in ('viewer-ui.js','viewer-ui.css','furniture-data.js','furniture-core.js','furniture-app.js','furniture.css','家具清單.json'):
        if required not in site: raise ValueError('Missing shared interface dependency: '+required)
    return count

def ignore_text(repo):
    allow = set(repo)
    for name in repo:
        allow.update(parent.as_posix()+'/' for parent in PurePosixPath(name).parents if str(parent) != '.')
    return '# Generated by tools/build-site.py --sync-ignore from .github/publish-files.json.\n# Local PDFs, backups, AI input images and temporary files remain on disk.\n*\n' + ''.join('!/'+name+'\n' for name in sorted(allow))

def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--output'); parser.add_argument('--sync-ignore',action='store_true'); parser.add_argument('--check',action='store_true')
    args = parser.parse_args(); data, site, repo = entries(); links = verify(site)
    expected = ignore_text(repo)
    if args.sync_ignore: (ROOT/'.gitignore').write_text(expected,encoding='utf-8')
    elif (ROOT/'.gitignore').read_text(encoding='utf-8') != expected: raise ValueError('Run --sync-ignore after changing the publication manifest')
    if args.output:
        output = (ROOT/args.output).resolve()
        if output == ROOT or ROOT not in output.parents or output.name != '_site': raise ValueError('Output must be a dedicated _site directory inside this project')
        if output.exists() and any(output.iterdir()): raise ValueError('Output must be empty; existing output will not be deleted')
        for name in sorted(site):
            target=output/name; target.parent.mkdir(parents=True,exist_ok=True); shutil.copy2(ROOT/name,target)
        copied={p.relative_to(output).as_posix() for p in output.rglob('*') if p.is_file()}
        if copied != site: raise ValueError('Site artifact differs from allowlist')
    site_bytes=sum((ROOT/name).stat().st_size for name in site); repo_bytes=sum((ROOT/name).stat().st_size for name in repo)
    print(json.dumps({'site_files':len(site),'site_MB':round(site_bytes/1048576,2),'repository_files':len(repo),'repository_MB':round(repo_bytes/1048576,2),'checked_HTML_links':links},ensure_ascii=False))

if __name__ == '__main__': main()
