"""Build the public QA03 comparison page from actual current and previous gallery assets."""
from pathlib import Path
import json
P=Path(__file__).resolve().parents[1];R=P/'調整紀錄/20260922全版本模型與AI複核';A=P/'成品圖集/20260914暗色現代工業'
read=lambda p:json.loads(p.read_text(encoding='utf8'))
old={e['key']:e for e in read(R/'album-before.json')['entries']};current=read(A/'album-manifest.json')['entries'];initial={e['key']:e for e in read(R/'初輪逐圖核對.json')['entries']}
names={'entry':'玄關','living':'客廳','island':'中島','kitchen':'廚房','bed':'主臥','closet':'更衣室','study':'雙人書房','collection':'收藏室','bath1':'主浴','bath2':'客浴','storage':'儲藏室','back':'後陽台'}
prefix='成品圖集/20260914暗色現代工業/'
rows=[]
for e in current:
 b=old[e['key']];changed=e['aiKey']!=b['aiKey'];room=names[e['room']]
 if e['version']=='v0' and e['room']=='collection':room='貓房'
 if e['version']=='v0' and e['room']=='study':room='書房・電子琴'
 if e['version'] in ['v3','v4'] and e['room']=='collection':room='開放收藏收納'
 rows.append({'key':e['key'],'version':e['version'],'room':e['room'],'label':e['version'].upper()+'｜'+room+'・'+e.get('directionLabel','方向 '+e['angle']),'changed':changed,'reason':initial[e['key']]['finding'],'before':prefix+'images/'+b['aiKey']+'.webp','model':prefix+'models/'+e['aiKey']+'.webp','after':prefix+'images/'+e['aiKey']+'.webp'})
html='''<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>W 夢想之家｜全版本模型與 AI 複核</title>
<style>*{box-sizing:border-box}body{margin:0;background:#141719;color:#ebebeb;font:16px/1.65 system-ui,"Microsoft JhengHei",sans-serif}main{max-width:1500px;margin:auto;padding:28px}a{color:#b8d4d7}header{display:flex;gap:24px;justify-content:space-between;flex-wrap:wrap;border-bottom:1px solid #3b4245;padding-bottom:16px}h1{font-size:clamp(28px,4vw,46px);line-height:1.25;margin:36px 0 12px}h2{font-size:22px}p{max-width:1040px;color:#c8ced1}.eyebrow{color:#99b6bb;font-size:13px;letter-spacing:.1em}.stats{display:flex;flex-wrap:wrap;gap:40px;margin:28px 0}.stats b{font-size:32px;margin-right:10px;color:white}.note,.findings{border:1px solid #3b4245;border-radius:14px;padding:20px;background:#1c2023}.findings{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.findings p{margin:5px 0}.findings b{color:#e3ecee}.toolbar{position:sticky;top:0;z-index:2;background:#141719f5;padding:16px 0;border-bottom:1px solid #3b4245;display:flex;align-items:center;flex-wrap:wrap;gap:12px}select,button{background:#242b2f;color:white;border:1px solid #626e74;border-radius:6px;padding:9px 13px;font:inherit}button{cursor:pointer}button[aria-pressed="true"]{background:#c0d6d7;color:#172023}label{display:flex;align-items:center;gap:8px}.status{color:#a7c6bb;font-size:14px}article{margin:28px 0 42px;border-bottom:1px solid #343b3f;padding-bottom:28px}article h3{margin:0;font-size:22px}article p{margin:6px 0 12px}.pictures{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.pictures.single{grid-template-columns:1fr;max-width:1200px;margin:auto}figure{margin:0;min-width:0}figcaption{padding:8px 0;color:#c8ced1}figure a{display:block}img{display:block;width:100%;height:auto;aspect-ratio:3/2;object-fit:contain;background:#22282c;border:1px solid #3b4245;border-radius:5px}footer{border-top:1px solid #3b4245;margin-top:40px;padding:24px 0;color:#9ba6ac}.empty{padding:40px}input[type="checkbox"]{width:18px;height:18px;accent-color:#b8d4d7}:focus-visible{outline:3px solid #e9c586;outline-offset:3px}@media(max-width:700px){main{padding:16px}.pictures,.findings{grid-template-columns:1fr}.toolbar{position:static}.stats{gap:20px}.stats b{font-size:26px}select,button{font-size:14px}.pictures.single{max-width:none}}</style></head>
<body><main><header><a href="index.html">W 夢想之家・互動 3D</a><a href="AI寫實視角.html">五版完整圖集 ↗</a></header>
<p class="eyebrow">2026.09.22 · QA03 · V0–V4</p><h1>同一個家，逐角度核對。</h1>
<p>重新取景並檢視五版全屋：入口每版 5 向，其餘 11 個空間各 3 向。先補模型缺口，再以修正模型重製 AI 圖；保留沒有發現主要配置偏差的既有圖。</p>
<div class="stats"><span><b>190</b>已核對角度</span><span><b>41</b>新 AI 成品</span><span><b>56</b>更新圖位</span><span><b>134</b>核對後保留</span></div>
<section class="findings" aria-label="本輪修正"><div><b>主浴｜外窗上下補回實牆</b><p>原模型只畫出窗框及玻璃，窗下缺少牆，造成落地窄窗的錯覺。本次保留窗位置與框線，補齊窗臺下及窗上牆體。窗臺 90 cm、窗頂 230 cm 為既有模型值，尚待核定立面／現場確認。</p></div><div><b>書房、廚房｜補齊玻璃開口上方</b><p>補回書房外窗上方、廚房通後陽台玻璃上方的缺漏實牆。牆、窗、梁及設備位置保留，沒有另外增加開窗。</p></div><div><b>V0 廚房｜水槽改為真正凹槽</b><p>去除水槽內部被檯面與櫃板封住的部分，保留既有外徑與位置；V1–V4 已有同類修正。內膽與開孔仍須對已下單廚具模板。</p></div><div><b>AI 圖｜補回、刪除及校正</b><p>修正 V4 入口漏水槽／龍頭、包包錯位、無中生有的盆栽，以及陽台誤封閉。新圖驗收再去除多餘杯盤／冷氣，恢復展示櫃玻璃、設備面板及正確地板。</p></div></section>
<p class="note">V1 高玻璃櫃與外弧兩凳、GB-R04 客浴收納均保留。V1–V4 共 62 組門片／面板各取 91 個姿態，主浴雙門每版 961 組狀態，及既有取物、通行路徑抽樣未檢出碰撞。V0 保留原始配置供比較，未套用後續動線改案。這是現有模型與圖集角度的檢視，不代表所有可能視角、人體使用或施工驗收。</p>
<section aria-label="逐圖對照"><h2>選版本與空間，查看修改前後</h2><div class="toolbar"><label>版本<select id="version"><option value="all">全版本</option><option value="v0">V0</option><option value="v1">V1</option><option value="v2">V2</option><option value="v3">V3</option><option value="v4">V4</option></select></label><label>空間<select id="room"><option value="all">全屋</option>__OPTIONS__</select></label><label><input type="checkbox" id="changed" checked>只看本次更新</label><button data-mode="compare" aria-pressed="true">模型／新 AI</button><button data-mode="beforeafter" aria-pressed="false">修改前／修改後</button><button data-mode="after" aria-pressed="false">只看新 AI</button><span id="count" role="status"></span></div><p>點圖片開啟原尺寸。不同版本只有在模型取景完全相同時才共用同一張 AI 圖。</p><div id="views"></div></section>
<footer>AI 圖為材質、照明與氣氛示意；收藏物造型、五金、細部接縫、反射及窗外景色不作施工依據。精確尺寸須回到核定圖說與現場。先前 AR02／MR01 對照保留為歷史紀錄，本頁與目前圖集採 QA03。</footer>
</main><script>
const rows=__DATA__;const $=s=>document.querySelector(s);let mode='compare';const params=new URLSearchParams(location.search);for(const id of ['version','room'])if([...$('#'+id).options].some(o=>o.value===params.get(id)))$('#'+id).value=params.get(id);
function render(){const version=$('#version').value,room=$('#room').value,changed=$('#changed').checked;const shown=rows.filter(r=>(version==='all'||r.version===version)&&(room==='all'||r.room===room)&&(!changed||r.changed));$('#count').textContent=shown.length+' 個角度';$('#views').replaceChildren();for(const r of shown){const card=document.createElement('article'),h=document.createElement('h3'),status=document.createElement('span'),p=document.createElement('p'),pics=document.createElement('div');h.textContent=r.label;status.className='status';status.textContent=r.changed?'本次重製':'逐圖核對後保留';p.textContent=r.reason;pics.className='pictures'+(mode==='after'?' single':'');const sources=mode==='compare'?[['model','本輪模型取景'],['after','目前 AI 示意']]:mode==='beforeafter'?[['before','修改前 AI'],['after','目前 AI 示意']]:[['after','目前 AI 示意']];for(const [field,label]of sources){const figure=document.createElement('figure'),caption=document.createElement('figcaption'),link=document.createElement('a'),img=document.createElement('img');caption.textContent=label;link.href=r[field];link.target='_blank';link.rel='noopener';link.setAttribute('aria-label','開啟 '+r.label+' '+label+' 原尺寸');img.src=r[field];img.alt=r.label+' '+label;img.loading='lazy';img.width=1152;img.height=768;link.append(img);figure.append(caption,link);pics.append(figure);}card.append(h,status,p,pics);$('#views').append(card);}if(!shown.length){const p=document.createElement('p');p.className='empty';p.textContent='這個篩選範圍沒有重製圖。取消「只看本次更新」即可查看已核對保留的角度。';$('#views').append(p);}}
for(const id of ['version','room','changed'])$('#'+id).addEventListener('change',render);for(const button of document.querySelectorAll('[data-mode]'))button.addEventListener('click',()=>{mode=button.dataset.mode;for(const b of document.querySelectorAll('[data-mode]'))b.setAttribute('aria-pressed',String(b===button));render();});render();
</script></body></html>'''
html=html.replace('__OPTIONS__',''.join(f'<option value="{k}">{v}</option>' for k,v in names.items())).replace('__DATA__',json.dumps(rows,ensure_ascii=False,separators=(',',':')))
(P/'全版本複核.html').write_text(html,encoding='utf8',newline='\n')
print(json.dumps({'reviewSlots':len(rows),'changedSlots':sum(r['changed'] for r in rows)},ensure_ascii=False))
