from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import json,math
P=Path(__file__).resolve().parents[1];R=P/'調整紀錄/20260922灰石全屋';A=P/'成品圖集/20260914暗色現代工業'
read=lambda p:json.loads(p.read_text(encoding='utf8'))
captures=read(R/'captures.json');seed=read(R/'首批提示.json')
common="""Use case: sketch-to-render. Make one 1536x1024 photorealistic architectural interior photograph by rendering ONLY the supplied model image. The model is a strict geometry AND material-location map. Preserve exact camera, framing, foreground occlusion, walls, beams, windows, doors, furniture shapes, cabinet divisions, equipment and object counts. Match the material class and color of EACH modeled surface. Gray flat floors are GRAY TILE; only floors already showing a wood pattern are gray-brown HERRINGBONE WOOD with reduced red/orange. Plain gray walls and pillars remain smooth gray paint, NOT stone. Opaque black/gray cabinet fronts stay opaque black/gray. Wood-grained surfaces stay desaturated gray-brown timber. Glass cabinet fronts stay transparent; a double-sided island glass cabinet has glass on BOTH sides and no opaque backing. Gray humanoid proxies in displays are real collectible figures: retain each visible figure in its compartment; do not empty the shelves or merge compartments. Lighting is restrained daylight plus the EXISTING fixtures, realistic soft shadows and material reflections. Do not introduce stone except where an actual textured stone feature panel is shown directly behind an existing TV or inside the fixed SOUTH display cabinet. Do not add lamps, plumbing, windows, furniture, decorative objects, people or extra openings. Real fine textures and photographed depth, not a flat CAD render, illustration or clay model. No text or watermark. All dimensions remain visually identical to the supplied image."""
notes={
'entry':'Entrance view. Preserve the exact closed storage fronts, display glazing, entry door and sight lines to other rooms. Gray entry stone/tile footprint and gray-brown herringbone boundary are exactly as shown. Upper and lower opaque cabinet areas remain closed storage. Gray stone appears only on the existing marked feature surface if visible beyond. Do not change cabinet height.',
'living':'Living room. Keep all loudspeakers, subwoofers, sofa, coffee table, TV mounting and AV rack exactly where shown. The herringbone floor, woven rug and smooth black hard coffee table are different surfaces. Fixed gray stone panels, when visible, have fine relief and understated horizontal staggered joints with existing top wash light; never cover cabinetry with stone or replace glass displays by walls.',
'island':'Island. Preserve exact footprint, curved or rectangular shape, cabinet fronts, factory appliances, faucets, induction hob and actual hollow sinks. Island counter is HONED FINE GRAY STONE, not rough feature-wall stone. Keep every clear tall glass cabinet wherever shown. V1 has exactly two round stools along the OUTER ARC, not between counter and high glass cabinet. Never add dining seats in other versions. Gray-brown vertical timber and silver brushed metal remain distinct.',
'kitchen':'Galley kitchen. CRITICAL: the ENTIRE galley floor is smooth GRAY TILE, absolutely no wood or herringbone inside the kitchen. Its factory cabinet fronts and surrounds are BLACK / DARK CHARCOAL / stainless as the image, NOT timber. The white outdoor units seen through glass with black circles are AIR CONDITIONER CONDENSERS with fan grilles, NOT washing machines. No round washer doors on these condensers. Preserve factory appliance colors including white refrigerator fronts and exact sink, hob, hood, cabinetry and glass back-balcony opening. Hollow stainless sink basin, water tap and worktop remain distinct. No island in the narrow galley, no additional appliances, wall ovens or new windows. Equipment counts unchanged.',
'bed':'Bedroom. Preserve tall gray-brown timber cabinetry, gray-taupe upholstered headboard, lower drawers, vanity and stool. The white object with a black circular lens on the OUTER upper shelf is a projector. Projection screen on the opposite wall is a blank matte pull-down screen, NOT a window or television. No stone feature wall, no extra bedside lamps or decor; keep two pillows and original bed location.',
'closet':'Walk-in wardrobe. Keep every shelf, drawer, hanging rail, sliding mirror and doorway exactly as shown. Gray simplified hanging shapes become realistic modest neutral hanging garments, and soft storage boxes become fabric organizers of the same footprint. Do not invent extra shelves or clothes racks. The pale full-height framed panel is a MIRROR, not a new window. Mirror reflection must show this same compact wardrobe, without expanding room geometry.',
'study':'Study. Keep both workstations where visible, monitor shapes, desktop PC towers, ergonomic chairs, exact glass display divisions, closed drawers and tall upper cabinets. Replace simple figure proxies by modest neutral collectible figures in those same footprints and numbers; no new collections. Black desks and gray-brown wood; comfortable neutral working light, restrained display light. No new stone wall or windows. V0 includes an electronic piano where shown; other versions retain their shown desks.',
'collection':'Collection/storage space. Preserve all closed practical-storage doors, glass showcase divisions, shelves and room walls. Geometric figures become modest detailed collectible figures in the same footprints and number; bag proxies become realistic bags without new compartments. Large box proxies become plain cardboard storage cartons at their existing sizes, not new furniture. Gray-brown wood and graphite frames. Never erase a backing panel to make room appear larger.',
'bath1':'Main bathroom. Mirror is reflective glass, not a window. The actual framed exterior window retains its SOLID WALL BELOW AND ABOVE as shown; never introduce floor-to-ceiling glazing or any extra window. Keep shower glazing/door geometry, toilet, tub and washbasin exactly where visible. Sink basin is hollow white ceramic. Bathroom floor is gray tile, NOT timber; any timber visible through the bedroom door stays only in that adjacent room. Fine gray wet-area finish, not coarse split-face stone. No new shower heads or plumbing.',
'bath2':'Guest WC has NO SHOWER and NO WINDOW. Every bright framed panel above the washbasin is a MIRROR reflecting this room, not exterior glazing. Preserve toilet, oval hollow white sink, faucet, vanity, overhead opaque supplies cabinet. The small platform on the TOILET SIDE of the vanity holds a flat black phone; the cassette BELOW that platform dispenses a single white tissue sideways. Keep it attached to the vanity side, not a new freestanding cabinet or wall cutout. Gray tiled floor, fine gray walls, no additional plumbing.',
'storage':'Utility storage room. Preserve the open adjustable metal shelves and empty access area as shown; no new objects, clothes, appliances or cabinets. Closed room doorway provides privacy. Neutral gray utilitarian walls and existing floor material; no decorative stone feature wall, no hotel styling. Light must remain plausible without inventing windows.',
'back':'Service balcony. Preserve exact air-conditioner outdoor condensers, fan counts, washer/dryer units where visible, service sink and safety parapet/rail. Large white rectangles with black circles are mechanical equipment, not TVs, speakers or washing machines unless actually the depicted washer tower. No new equipment, wooden deck, timber floor, plants or closed glazing. Basin and mirror are separate, mirror is not a new door. Practical gray floor with subdued outdoor daylight.'}
groups={}
for e in captures:groups.setdefault(e['modelHash'],[]).append(e)
jobs=[]
for h,es in groups.items():
 e=es[0];key=e['key']+'-gr06';prompt=common+'\nRoom-specific constraints: '+notes[e['room']]
 if e['version']=='v0' and e['room']=='collection':prompt=common+'\nRoom-specific constraints: Original-layout cat room. Keep the exact wall-mounted cat steps, scratch post and enclosed litter/storage furniture. No cat or person, no added glass showcase. Soft gray walls, easy-clean black furniture and gray-brown herringbone floor. Never add a window.'
 if e['version'] in ['v0','v1'] and e['room']=='living':prompt+=' Keep the full upper and right-hand opaque TV storage cabinetry. Stone is only the panel BELOW the upper cabinet; do not demolish storage.'
 if e['version'] in ['v2','v3'] and e['room'] in ['living','entry','island']:prompt+=' This version has a ROTATING metal TV mechanism: preserve its slim metal mounting and exact orientation. Gray stone belongs only to the FIXED backing of the existing tall GLASS display wall. Do not make the TV mount out of stone and do not remove glass or shelves.'
 if e['room']=='bed' and e['angle']=='E':prompt+=' View is seated on the bed toward the existing blank projection screen, not a missing TV; preserve low camera and adjacent door views.'
 known=next((j for j in seed if j['key']==key),None)
 if known:prompt=known['prompt']
 prompt=prompt.replace('Gray humanoid proxies in displays are real collectible figures: retain each visible figure in its compartment; do not empty the shelves or merge compartments. ', 'Preserve exact shelf contents: empty shelves stay EMPTY. Never add figures, appliances or objects to empty cabinets. ')
 if e['room'] in ['bed','closet']:
  prompt+=' All visible BEDROOM and WARDROBE floor areas are gray-brown HERRINGBONE WOOD, absolutely no tile inside bedroom or wardrobe. Any hanging thin gray rectangular slabs in the wardrobe are GARMENT PLACEHOLDERS: turn EACH slab into one realistic hanging coat on a shared rail; do NOT draw solid vertical partitions between garments.'
 if e['room']=='collection' and e['version']!='v0':
  prompt=prompt.replace('Geometric figures become modest detailed collectible figures in the same footprints and number; bag proxies become realistic bags without new compartments. ', '')
  prompt+=' Floor is gray-brown HERRINGBONE WOOD, not tile. Empty glass cabinets must remain empty. Where the model explicitly shows a pale rectangular torso topped by a sphere INSIDE the public-facing wall showcase, this is a collectible toy: render one simple neutral humanoid designer toy with small arms, legs and round head at that exact size, not a sphere balanced on a stone plinth. Do not add figures where there are no sphere-torso proxies. Storage BACK sides contain boxes only, NO figures.'
 if e['room']=='storage':prompt+=' All adjustable shelf boards are smooth MATTE LIGHT GRAY METAL, no wood grain on shelves. Only the floor is gray-brown timber.'
 if e['room']=='study':
  prompt+=' Collectible figures ONLY belong inside glass showcase compartments where visibly modeled. Do NOT add toys to computer desktops. The sphere on a short stem on the sofa console in the distant living room is a dark gray ROUND SURROUND SPEAKER, not a figurine: it has no arms or legs.'
 if e['room']=='kitchen':
  prompt=prompt.replace('The white outdoor units seen through glass with black circles are AIR CONDITIONER CONDENSERS with fan grilles, NOT washing machines. No round washer doors on these condensers. ', '')
  prompt+=' Empty pantry shelves must remain empty. Do NOT add any appliance to an interior display cabinet. Only render outdoor equipment when it is VISIBLE in the model: count and locate each visible unit, with fan grilles, without adding units or a washing-machine drum.'
 if e['version']=='v1' and e['room'] in ['island','living','entry']:
  prompt+=' The tall transparent cabinet ATTACHED TO THE ISLAND is nearly EMPTY except the single vase where visible: absolutely no collection figures or solid backing inside this island cabinet. A SEPARATE wall showcase contains figures only in the exact existing compartments. Preserve contents of all other cabinets exactly.'
 if e['version']=='v1' and e['room']=='island' and e['angle']=='E':prompt+=' The separate collection wall behind the island has EXACTLY FIVE vertical glass columns with TWO figures per column: TEN figures total. Preserve all FIVE columns and both horizontal display tiers, including the fifth column at the far right.'
 if e['room']=='entry' and e['angle']=='A':prompt+=' This close frame is mostly a blank solid gray wall with dark borders. Preserve that occlusion exactly; do not invent furniture, television, doorway or extra stone panel.'
 jobs.append({'key':key,'sourceKey':e['key'],'room':e['room'],'version':e['version'],'angle':e['angle'],'name':e['name'],'modelHash':h,'modelPath':str((R/e['model']).resolve()),'prompt':prompt,'mappedViews':[q['key'] for q in es]})
assert all(j['prompt'] and 'undefined' not in j['prompt'] for j in jobs)
(R/'jobs.json').write_text(json.dumps(jobs,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
font=ImageFont.truetype('C:/Windows/Fonts/msjh.ttc',20)
for start in range(0,len(jobs),6):
 canvas=Image.new('RGB',(1728,816),'#202226');d=ImageDraw.Draw(canvas)
 for i,j in enumerate(jobs[start:start+6]):
  x=i%3*576;y=i//3*408
  with Image.open(j['modelPath']) as im:canvas.paste(im.resize((576,384)),(x,y+24))
  d.text((x+5,y),j['key'],font=font,fill='white')
 canvas.save(R/f'sources-{start//6+1:02}.jpg',quality=95)
print(json.dumps({'slots':len(captures),'unique':len(jobs),'pages':math.ceil(len(jobs)/6),'generated':len(list((R/'ai').glob('*.png')))},ensure_ascii=False))
