from pathlib import Path
import json
P=Path(__file__).resolve().parents[1];R=P/'調整紀錄/20261001全版本化妝桌VT02'
jobs=json.loads((R/'jobs.json').read_text(encoding='utf8'))
base='''Use case: precise-object-edit. Produce a photorealistic residential interior photograph for an existing design gallery. Image 1 is the EDIT TARGET: preserve its entire camera, framing, room geometry, furniture, lighting and material quality. Image 2 is the authoritative UPDATED 3D GEOMETRY at the same exact camera. Image 3 is a close-up DESIGN REFERENCE for the new vanity only, not the camera or room composition.
Change ONLY the existing window-side vanity to the adopted glass-topped dark graphite vanity. Its original footprint stays identical. Transparent glass desktop with thin gunmetal edging; two end pedestals each with an upper transparent perfume compartment and TWO opaque graphite drawers below; shallow compartmented jewelry tray beneath the central front glass; central open knee space and the existing square upholstered stool. Central rear mirror lid is opaque graphite, FLUSH AND CLOSED. No upright mirror, no tabletop monitor, no open drawers. Perfumes stay inside the end compartments beneath the glass, never on top. The reference is a design concept, do not copy its text label. Match Image 2's position, projection and visible portion precisely. Preserve black ceiling and beams, gray walls, gray-brown herringbone floor, bed, wood headboard storage, projector and white projection screen, door opening and background specific to Image 1. No added objects or windows. Window exterior when visible should be a soft neutral out-of-focus bright placeholder, not a fabricated detailed cityscape. High-quality realistic glass edges, refraction, subtle metal, textiles and contact shadows. No text, no watermark. Output single landscape photograph, same 3:2 framing as Image 1.
'''
for j in jobs:
 note={'A':'This is a wide view toward the headboard. The vanity is at the LEFT EDGE, partly cropped. Keep the bed and full headboard exactly fixed. Remove the old standing vanity mirror at left. Do NOT recenter the room onto the vanity.', 'C':'This is the wide view across the bed toward the window. Replace the complete wood vanity beneath the window and remove the old small standing mirror. Keep the bed foreground, large white projection screen on the left wall and the wood headboard cabinets on the right. The new vanity remains at the far end, not enlarged toward the camera.', 'E':'This is the bed-eye view toward the white projection screen. ONLY A SMALL END OF THE VANITY is visible at the FAR RIGHT EDGE near the open black door. Replace that small visible wood cabinet sliver with the new graphite drawers and glass perfume compartment, following Image 2 exactly. The vanity is mostly OUTSIDE THE FRAME. Do not invent a vanity under the screen or change framing to reveal more of it. Preserve all of the screen, partition, door opening, black door, the particular hall scene visible through both side openings and the bed foreground.'}[j['angle']]
 prompt=base+'\n'+note+'\n'
 (R/'prompts'/f"{j['key']}.txt").write_text(prompt,encoding='utf8')
 j['prompt']=prompt
 j['references']=[str(P/'成品圖集/20260914暗色現代工業/images'/f"{j['oldAI']}.webp"),str(R/j['source']),str(P/'評估/20261001玻璃化妝桌VT01/VT01-01_鏡子收起.png')]
(R/'generation-jobs.json').write_text(json.dumps(jobs,ensure_ascii=False,indent=2),encoding='utf8')
print('Prepared',len(jobs),'complete prompts')
